{% set version = "2.3.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-fdasrvf
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/fdasrvf_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/fdasrvf/fdasrvf_{{ version }}.tar.gz
  sha256: e8814d95da4a0482cad642d3ebfc33393946d9832e614944ebe2f24cb036a491

build:
  merge_build_host: true  # [win]
  number: 0
  skip: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-matrix
    - r-rcpp
    - r-rcpparmadillo
    - r-cli
    - r-coda
    - r-doparallel
    - r-fields
    - r-foreach
    - r-lpsolve
    - r-mvtnorm
    - r-rlang
    - r-tolerance
    - r-viridislite
    - libblas
    - liblapack
    - libgomp                      # [linux]
    - llvm-openmp
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-matrix
    - r-rcpp
    - r-rcpparmadillo
    - r-cli
    - r-coda
    - r-doparallel
    - r-fields
    - r-foreach
    - r-lpsolve
    - r-mvtnorm
    - r-rlang
    - r-tolerance
    - r-viridislite
    - libblas
    - liblapack
    - llvm-openmp

test:
  commands:
    - $R -e "library('fdasrvf')"           # [not win]
    - "\"%R%\" -e \"library('fdasrvf')\""  # [win]

about:
  home: https://github.com/jdtuck/fdasrvf_R
  license: GPL-2.0-or-later
  summary: Performs alignment, PCA, and modeling of multidimensional and unidimensional functions using the square-root velocity framework (Srivastava et al., 2011 <arXiv:1103.3817> and Tucker et al., 2014 <DOI:10.1016/j.csda.2012.12.001>). This framework allows for elastic analysis of functional data through phase and amplitude
    separation.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - jdtuck

# Package: fdasrvf
# Type: Package
# Title: Elastic Functional Data Analysis
# Version: 2.1.2
# Date: 2023-12-20
# Authors@R: c( person(given = "J. Derek", family = "Tucker", role = c("aut", "cre"), email = "jdtuck@sandia.gov", comment = c(ORCID = "0000-0001-8844-2169")), person(given = "Aymeric", family = "Stamm", role = "ctb", email = "aymeric.stamm@math.cnrs.fr", comment = c(ORCID = "0000-0002-8725-3654")))
# Description: Performs alignment, PCA, and modeling of multidimensional and unidimensional functions using the square-root velocity framework (Srivastava et al., 2011 <arXiv:1103.3817> and Tucker et al., 2014 <DOI:10.1016/j.csda.2012.12.001>). This framework allows for elastic analysis of functional data through phase and amplitude separation.
# License: GPL-3
# LazyData: TRUE
# Imports: cli, coda, doParallel, fields, foreach, lpSolve, Matrix, mvtnorm, Rcpp, rlang, tolerance, viridisLite
# Suggests: covr, interp, plot3D, plot3Drgl, rgl, testthat (>= 3.0.0), withr
# Depends: R (>= 4.1.0),
# RoxygenNote: 7.2.3
# Encoding: UTF-8
# Config/testthat/edition: 3
# LinkingTo: Rcpp, RcppArmadillo
# URL: https://github.com/jdtuck/fdasrvf_R
# BugReports: https://github.com/jdtuck/fdasrvf_R/issues
# NeedsCompilation: yes
# Packaged: 2023-12-21 11:15:05 UTC; jdtuck
# Author: J. Derek Tucker [aut, cre] (<https://orcid.org/0000-0001-8844-2169>), Aymeric Stamm [ctb] (<https://orcid.org/0000-0002-8725-3654>)
# Maintainer: J. Derek Tucker <jdtuck@sandia.gov>
# Repository: CRAN
# Date/Publication: 2023-12-21 12:00:04 UTC
